DROP TABLE IF EXISTS books;

CREATE TABLE books(
id INT AUTO_INCREMENT PRIMARY KEY,
authorId INT NOT NULL,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS authors;

CREATE TABLE authors(
id INT AUTO_INCREMENT PRIMARY KEY,
fullName VARCHAR(250) NOT NULL
);

ALTER TABLE books
ADD CONSTRAINT FK_AuthorBooks
FOREIGN KEY (authorId) REFERENCES authors(id);
